CleverTap/clevertap-android-sdk

docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

Android 11 support scheduled for next release.

Remove android 11 support, scheduled for next release

---

sample/build.gradle
sample/src/main/assets/sampleHTMLCode.html
sample/src/main/java/com/clevertap/demo/HomeScreenActivity.kt
sample/src/main/java/com/clevertap/demo/MyApplication.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenFragment.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt
sample/src/main/res/layout/home_screen_activity.xml

Updates Sample App with Inbox and WebView enhancements

SDK-777 Update Sample App for Release v4.1.1

---

gradle-scripts/commons.gradle

Merge pom dependency fix to develop

Fix/maven pom/sdk-773

---

clevertap-core/src/main/java/com/clevertap/android/sdk/ActivityLifeCycleManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/DeviceInfo.java
clevertap-core/src/main/java/com/clevertap/android/sdk/validation/ManifestValidator.java

This PR contains fixes added for console and GitHub issues.Following are issues which are fixed:-
CTBackgroundJobService crash on Android 4.4 SDK-779
NPE on InstallReferrer code silent crash SDK-780
Notification Enabled Crash on SDK Console SDK-781

Task/GitHub issues/sdk 778

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CTInboxStyleConfig.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java

Adds `setFirstTabTitle` method to `CTInboxStyleConfig` class

SDK-601 Inbox Enhancements

---

CHANGELOG.md
README.md
clevertap-core/src/main/java/com/clevertap/android/sdk/CTWebInterface.java
clevertap-core/src/main/java/com/clevertap/android/sdk/Utils.java
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTXIAOMIPUSH.md
docs/CTXIAOMIPUSHCHANGELOG.md
docs/EXAMPLES.md
gradle-scripts/commons.gradle
gradle-scripts/versions.gradle
gradle/wrapper/gradle-wrapper.properties
templates/CTCORECHANGELOG.md
templates/CTXIAOMIPUSHCHANGELOG.md
templates/EXAMPLES.md

Adds Charged Event in `CTWebInterface`

SDK-603 WebView Enhancements

---

clevertap-core/src/main/java/com/clevertap/android/sdk/ControllerManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBAdapter.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxController.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxMessage.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxMessageContent.java
clevertap-core/src/main/java/com/clevertap/android/sdk/response/CleverTapResponse.java
clevertap-core/src/main/java/com/clevertap/android/sdk/response/InboxResponse.java
clevertap-core/src/main/res/layout-land/inbox_carousel_text_layout.xml
clevertap-core/src/main/res/layout/inbox_simple_message_layout.xml
sample/src/main/res/layout/home_screen_activity.xml

- Added annotations
- Added fix for app inbox

Optimise app inbox SDK-849

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CoreMetaData.java
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

- fix record screen NPE
- add record screen button in sample app

fix record screen NPE SDK-803

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
docs/CTHUAWEIPUSH.md
sample/src/main/java/com/clevertap/demo/HomeScreenActivity.kt
templates/CTHUAWEIPUSH.md

Add VERBOSE log level to LogLevel enum public API

Add VERBOSE log level to CleverTapAPI SDK-873

---

sample/src/main/java/com/clevertap/demo/MyApplication.kt

Removed strict mode setting code from sample app

task(async_deviceID): remove strict mode logging SDK-934

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

Updated changelogs with latest release date

chore(changelogs): update changelogs SDK-956

---

clevertap-core/src/main/AndroidManifest.xml

Remove bg sync metadata from core manifest

merge android12_support-core_sdk to develop

---

clevertap-core/src/main/java/com/clevertap/android/sdk/ActivityLifeCycleManager.java

Reverts CleverTap/clevertap-android-sdk#224

Revert "[github issue #221] moving onPause to background thread"

---

clevertap-core/src/main/java/com/clevertap/android/sdk/AnalyticsManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/events/BaseEventQueueManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventQueueManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/login/LoginInfoProvider.java
clevertap-core/src/test/java/com/clevertap/android/sdk/AnalyticsManagerTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/EventQueueManagerTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/LoginInfoProviderTest.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

Remove Specific User Properties from databases, Shared Preference, and elsewhere(arp etc) stored in the SDK ensuring no impact on Identity Management / onUserLogin.

[SDK-1620]-Remove PII data using `removeValueForKey`

---

CHANGELOG.md
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushConstants.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/UnregistrableCTPushProvider.java
clevertap-core/src/main/java/com/clevertap/android/sdk/utils/PackageUtils.java
clevertap-xps/src/main/java/com/clevertap/android/xps/IMiSdkHandler.java
clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiPushProvider.java
clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiSdkHandler.java
sample/src/main/java/com/clevertap/demo/MyApplication.kt
sample/src/main/res/values/strings.xml

- add public api `enableXiaomiPushOn(int xpsRunningDevices)` to run xiaomi sdk on all devices, xiaomi only devices or turn off push on all devices.

Feat/enable xps only for xiaomi devices/sdk 1644

---

docs/CTCORECHANGELOG.md
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/clevertap/demo/HomeScreenActivity.kt
sample/src/main/java/com/clevertap/demo/MyApplication.kt
sample/src/main/java/com/clevertap/demo/ui/main/NotificationUtils.kt
templates/CTCORECHANGELOG.md
templates/README.md

- Add `onNewIntent` for notification click callback on Android 12
- Add `onActivityCreated` for clearing notification  on Android 12

update sample for notification click callbacks SDK-1753

---

CHANGELOG.md

Update releases in Changelog.md

chore(SDK-1798)-Update main Changelog.md

---

clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/TemplateRenderer.kt
docs/CTPUSHTEMPLATESCHANGELOG.md
templates/CTPUSHTEMPLATESCHANGELOG.md

Fixes push impression not raised bug for TimerTemplate

SDK-1808/pt_timer_push_impression_issue

---

clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBManager.java
clevertap-core/src/test/java/com/clevertap/android/sdk/db/DBManagerTest.kt

[SDK-1785]
[SDK-1785]: https://wizrocket.atlassian.net/browse/SDK-1785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Unit Tests for DBManager.java

---

clevertap-core/src/main/java/com/clevertap/android/sdk/AnalyticsManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CoreMetaData.java
clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkManager.java

Make sure that callback will be given only when viewed event for latest push on device is sent to BE

send notification viewed callback for last push on device SDK-2129

---

CHANGELOG.md
README.md
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
clevertap-core/src/main/java/com/clevertap/android/sdk/InboxMessageListener.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java
clevertap-xps/src/main/AndroidManifest.xml
clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiMessageReceiver.java
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTHUAWEIPUSHCHANGELOG.md
docs/CTPUSHTEMPLATES.md
docs/CTPUSHTEMPLATESCHANGELOG.md
docs/CTXIAOMIPUSHCHANGELOG.md
sample/build.gradle
templates/CTCORECHANGELOG.md
templates/CTHUAWEIPUSHCHANGELOG.md
templates/CTXIAOMIPUSHCHANGELOG.md
versions.properties

- xps android 12 changes : adding additional activity in manifest
- ct core v4.6.1. : doc changes 
-  misc : bug fixes for : 
- blue dot bug fix

xps, android 12 changes and ct core sdk v 4.6.1

---

clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PushTemplateReceiver.java

- Add notification header subtitle on android 12 for input box in PushTemplateReceiver

fix(push-templates): add subtitle to notification header above android 12 SDK-2160

---

CHANGELOG.md

Update changelog for root package

chore(SDK-1970) - Update root CHANGELOG.md for release

---

docs/CTXIAOMIPUSH.md
templates/CTXIAOMIPUSH.md

Update the link to download the latest Mi push Library

chore[SDK-1970] - Update Xiaomi doc

---

CHANGELOG.md
docs/CTXIAOMIPUSH.md
templates/CTXIAOMIPUSH.md

Update the link to download the latest Mi push Library

Update XPS doc

---

README.md
build.gradle
buildSrc/src/main/kotlin/Libs.kt
docs/CTRENDERMAX.md
docs/CTRENDERMAXCHANGELOG.md
templates/CTRENDERMAX.md
templates/CTRENDERMAXCHANGELOG.md
templates/README.md
versions.properties

- Add documentation in README for renderMAX
- Add changelog for renderMAX

chore(SDK-2615) - add docs and changelog for renderMAX

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBasePartialFragment.java
clevertap-core/src/main/res/layout-land/inapp_footer.xml
clevertap-core/src/main/res/layout/inapp_footer.xml
clevertap-core/src/main/res/values-land/dimens.xml
clevertap-core/src/main/res/values-sw600dp-land/dimens.xml
clevertap-core/src/main/res/values-sw600dp/dimens.xml
clevertap-core/src/main/res/values-sw720dp-land/dimens.xml
clevertap-core/src/main/res/values-sw720dp/dimens.xml
clevertap-core/src/main/res/values/dimens.xml
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenFragment.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

- fix responsiveness of content part of footer in-app

Fix/in-app UI/SDK-2542

---

CHANGELOG.md
README.md
clevertap-core/src/main/java/com/clevertap/android/sdk/CTXtensions.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java
clevertap-core/src/test/java/com/clevertap/android/sdk/CTXtensionsTest.kt
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
sample/build.gradle
sample/src/main/java/com/clevertap/demo/MyApplication.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt
templates/CTCORECHANGELOG.md
versions.properties

- If notification channel is disabled then don't raise push impression

Fix/push impressions/SDK-2444

---

CHANGELOG.md
README.md
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
docs/CTRENDERMAX.md
docs/CTRENDERMAXCHANGELOG.md
templates/CTCORECHANGELOG.md
templates/CTRENDERMAXCHANGELOG.md
versions.properties

* Bug fixes and performance improvements.

Fix/rendermax anr/SDK-2667

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
docs/CTPUSHTEMPLATESCHANGELOG.md
docs/CTRENDERMAXCHANGELOG.md
templates/CTCORECHANGELOG.md
templates/CTPUSHTEMPLATESCHANGELOG.md
templates/CTRENDERMAXCHANGELOG.md

update changelog for core v4.6.7 and push templates v1.0.5.1 release

Update changelogs SDK-2779

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
docs/EXAMPLES.md
templates/CTCORECHANGELOG.md
templates/EXAMPLES.md

Update changelog for Core v4.6.8

[SDK-2826]: Update ChangeLog for Corev4.6.8

---

docs/EXAMPLES.md
templates/EXAMPLES.md

Updated the supported Core SDK versions for App Inbox in examples.md

[SDK-2830]: Update supported core versions for App Inbox

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
docs/EXAMPLES.md
templates/CTCORECHANGELOG.md
templates/EXAMPLES.md

Update ChangeLog and Example doc for Core v4.6.9 release.

[SDK-2881]: Update ChangeLog and Example doc for Core v4.6.9 release

---

clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkManager.java

- Makes the `minDelayFrequency` variable global to the class so that the retry mechanism logic works as intended
- Cleans up code

task(SDK-2575): Fix retry mechanism bug for non-EU1 regions

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBAdapter.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxController.java
clevertap-core/src/test/java/com/clevertap/android/sdk/CleverTapAPITest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/db/DBAdapterTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inbox/CTInboxControllerTest.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

https://wizrocket.atlassian.net/browse/SDK-2726
Add new APIs to App Inbox - markReadInboxMessagesForIDs and deleteInboxMessagesForIDs as in iOS

Task/sd 2726/new apis for app inbox

---

docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

chore(SDK-2941) - correct typo for variables.md

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/AlertDialogPromptForSettings.kt
docs/CTPUSHTEMPLATES.md
templates/CTPUSHTEMPLATES.md

- Adds `isCancellable` flag to the dialog builder which became unresponsive when clicked outside the window.
- Updates document changes under Image Specs for Push Templates SDK.

[SDK: 3016] : Push primer alert dialog freeze

---

docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

update  CTCORECHANGELOG SDK-3054

---

CHANGELOG.md

update CHANGELOG SDK-3054

---

clevertap-core/src/main/java/com/clevertap/android/sdk/AnalyticsManager.java

Change
```
final String command = (localDataStore.getProfileValueForKey(key) != null)
? Constants.COMMAND_ADD : Constants.COMMAND_SET;
```
to 
`final String command = Constants.COMMAND_ADD;`

Fix for addMultiValuesForKey SDK-3114

---

clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxMessage.java
clevertap-core/src/test/java/com/clevertap/android/sdk/inbox/CTInboxMessageTest.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

Apps can get custom Key values of inbox message as 
```
public JSONObject getCustomData() {
return customData;
}
```

feat(inbox) - Add custom key values in Inbox message SDK-3165

---

clevertap-xps/src/main/java/com/clevertap/android/xps/CTXiaomiMessageHandler.java
clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiMessageReceiver.java
clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiNotificationParser.java
clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiSdkHandler.java

Updates Logger implementation to static for XPS module

task(SDK-3215) - Updates Logger implementation to static for XPS module

---

clevertap-hms/src/main/java/com/clevertap/android/hms/CTHmsMessageHandler.java
clevertap-hms/src/main/java/com/clevertap/android/hms/CTHmsMessageService.java
clevertap-hms/src/main/java/com/clevertap/android/hms/HmsNotificationParser.java
clevertap-hms/src/main/java/com/clevertap/android/hms/HmsSdkHandler.java

Updates Logger implementation to static for HMS module

task(SDK-3215) - Updates Logger implementation to static for HMS module

---

clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkManager.java

This addition is part of the integration debugger feature

task(SDK-3204) - Adds debug key-value to meta object in header of payload

---

clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java

https://wizrocket.atlassian.net/browse/SDK-3320
Updates mutable flag to immutable for pending intents to resolve security vulnerability

task(SDK-3320) - Updates mutable flag to immutable for pending intents

---

clevertap-xps/src/main/java/com/clevertap/android/xps/XiaomiSdkHandler.java

Adds a check to see if app is foreground before initialising xps
https://wizrocket.atlassian.net/browse/SDK-3325

task(SDK-3325) - Adds foreground check before initializing XPS

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
docs/CTXIAOMIPUSHCHANGELOG.md
templates/CTCORECHANGELOG.md
templates/CTXIAOMIPUSHCHANGELOG.md

docs(SDK-3115) - Updates date for release

---

clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/TemplateRenderer.kt
clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/PendingIntentFactory.kt

Fixes image sequence issue for manual carousel. Also replaces lossy conversion to Random ints
https://github.com/CleverTap/clevertap-android-sdk/issues/488

task(SDK-3378) - Fixes image sequence issue for manual carousel

---

clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/INotificationRenderer.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/LaunchPendingIntentFactory.java

Changes lossy conversion in pending intent request codes to Random integer to avoid PushTemplate issue.
https://wizrocket.atlassian.net/browse/SDK-3381

task(SDK-3381) - Changes lossy conversion in request codes

---

clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/PendingIntentFactory.kt

Updates the pending intent flags which was leading to a vulnerability in pre-launch report

task(SDK-3343) - Update PendingIntent Flag mutable to immutable

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxMessageContent.java

https://wizrocket.atlassian.net/browse/SDK-3526

task(SDK-3526) - Removes restricted scope of CTInboxMessageContent class

---

clevertap-core/src/main/java/com/clevertap/android/sdk/cryption/CryptUtils.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/cryption/CryptUtilsTest.kt

https://wizrocket.atlassian.net/browse/SDK-3510

Task/sdk 3510/encryption migration db out of memory

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CTWebInterface.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFullHtmlFragment.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBasePartialHtmlFragment.java

https://wizrocket.atlassian.net/browse/SDK-3399

task(SDK-3399) - Supports JS for custom html header and footer inapps

---

CHANGELOG.md
README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
templates/CTCORECHANGELOG.md

Adds changelog and readme changes for corev5.2.2

task(SDK-3530) - Updates the docs and versions

---

clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java

This reverts commit 93599570e691ee95408bf434965f30f44850a52f.

Revert fix(push) - fix concurrent modification exception

---

clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java
gradle/libs.versions.toml

https://developer.android.com/about/versions/14/features/predictive-back#custom-activity

task(SDK-3629) - Handles deprecated overridePendingTransitionMethod()

---

clevertap-geofence/build.gradle
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTGeofenceAPITest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTGeofenceBootReceiverTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTGeofenceFactoryTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTGeofenceReceiverTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTGeofenceSettingsTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTGeofenceTaskManagerTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTLocationFactoryTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/CTLocationUpdateReceiverTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/GeofenceUpdateTaskTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/GoogleGeofenceAdapterTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/GoogleLocationAdapterTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/LocationUpdateTaskTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/PendingIntentFactoryTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/PushGeofenceEventTaskTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/PushLocationEventTaskTest.java
clevertap-geofence/src/test/java/com/clevertap/android/geofence/UtilsTest.java
gradle/libs.versions.toml
test_shared/build.gradle

Java 17 doesn't support powermock. Hence geofence tests have been refactored

Task/sdk 3639/refactor geofence unit tests

---

clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java

https://wizrocket.atlassian.net/browse/SDK-3536

task(SDK-3536) - Changes inapp fragment transaction to commitNow()

---

clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/PendingIntentFactory.kt

https://wizrocket.atlassian.net/browse/SDK-3634

task(SDK-3238) - Fixes Input PT by changing flag to MUTABLE

---

.github/workflows/on_pr_from_task_to_develop.yml

Git action improv to run static checks

Workflow: Git actions for static checks

---

clevertap-core/src/main/res/layout-land/inapp_cover.xml
clevertap-core/src/main/res/layout-land/inapp_cover_image.xml
clevertap-core/src/main/res/layout-land/inapp_footer.xml
clevertap-core/src/main/res/layout-land/inapp_half_interstitial.xml
clevertap-core/src/main/res/layout-land/inapp_half_interstitial_image.xml
clevertap-core/src/main/res/layout-land/inapp_header.xml
clevertap-core/src/main/res/layout-land/inapp_interstitial.xml
clevertap-core/src/main/res/layout-land/inapp_interstitial_image.xml
clevertap-core/src/main/res/layout-sw600dp-land/inapp_cover.xml
clevertap-core/src/main/res/layout-sw600dp-land/inapp_cover_image.xml
clevertap-core/src/main/res/layout-sw600dp-land/tab_inapp_half_interstitial.xml
clevertap-core/src/main/res/layout-sw600dp-land/tab_inapp_half_interstitial_image.xml
clevertap-core/src/main/res/layout-sw600dp-land/tab_inapp_interstitial.xml
clevertap-core/src/main/res/layout-sw600dp-land/tab_inapp_interstitial_image.xml
clevertap-core/src/main/res/layout-sw600dp/inapp_cover.xml
clevertap-core/src/main/res/layout-sw600dp/inapp_cover_image.xml
clevertap-core/src/main/res/layout-sw600dp/tab_inapp_half_interstitial.xml
clevertap-core/src/main/res/layout-sw600dp/tab_inapp_half_interstitial_image.xml
clevertap-core/src/main/res/layout-sw600dp/tab_inapp_interstitial.xml
clevertap-core/src/main/res/layout-sw600dp/tab_inapp_interstitial_image.xml
clevertap-core/src/main/res/layout/inapp_cover.xml
clevertap-core/src/main/res/layout/inapp_cover_image.xml
clevertap-core/src/main/res/layout/inapp_footer.xml
clevertap-core/src/main/res/layout/inapp_half_interstitial.xml
clevertap-core/src/main/res/layout/inapp_half_interstitial_image.xml
clevertap-core/src/main/res/layout/inapp_header.xml
clevertap-core/src/main/res/layout/inapp_interstitial.xml
clevertap-core/src/main/res/layout/inapp_interstitial_image.xml

Jira: https://wizrocket.atlassian.net/browse/SDK-3658

Task/sdk 3659/accessibility ids

---

gradle/libs.versions.toml

Updates libs.versions.toml
- agp version was wrong because of erroneous conflict resolve
- kotlin plugin version downgraded because of incompatibility

task(SDK-3620) - Updates AGP to 8.2.2

---

sample/build.gradle
sample/proguard-rules.pro
sample/src/main/java/com/clevertap/demo/ExampleVariables.java
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

https://wizrocket.atlassian.net/browse/SDK-3685
Support latest releases of clevertap sdk, hms, geofence and push-templates

task(SDK-3685) - Adds variables, CS InApps to sample app

---

CHANGELOG.md
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/interfaces/IPushAmpHandler.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/fcm/CTFcmMessageHandler.java
clevertap-core/src/main/java/com/clevertap/android/sdk/response/PushAmpResponse.java
clevertap-hms/src/main/java/com/clevertap/android/hms/CTHmsMessageHandler.java
clevertap-xps/src/main/java/com/clevertap/android/xps/CTXiaomiMessageHandler.java
docs/CTCORECHANGELOG.md
docs/CTHUAWEIPUSHCHANGELOG.md
docs/CTPUSHTEMPLATESCHANGELOG.md
docs/CTV4CHANGES.md
docs/CTXIAOMIPUSHCHANGELOG.md
docs/EXAMPLES.md
docs/FAQ.md
templates/CTCORECHANGELOG.md
templates/CTHUAWEIPUSHCHANGELOG.md
templates/CTPUSHTEMPLATESCHANGELOG.md
templates/CTV4CHANGES.md
templates/CTXIAOMIPUSHCHANGELOG.md
templates/EXAMPLES.md
templates/FAQ.md

Updates the docs and comments to not use the trademarked keyword

docs(SDK-3672) - Replaces trademarked keyword with Pull Notifications

---

CHANGELOG.md
README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
sample/build.gradle
templates/CTCORECHANGELOG.md

docs - Updates docs for hotfix v6.1.1

---

docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

https://clevertap.slack.com/archives/G01AZM6A2RK/p1709198690135149

docs - Updates docs for ClassNotFoundException in v6.1.1

---

CHANGELOG.md
README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
sample/build.gradle
sample/src/main/java/com/clevertap/demo/MyApplication.kt
templates/CTCORECHANGELOG.md

Updates CHANGELOG.md
Updates versions
Runs copyTemplates

Docs/sdk 3743/release ctv6.2.0

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

Updates core changelog for `v6.2.0`

update core changelog for `v6.2.0`

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapFactory.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CoreState.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotificationButton.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppType.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplate.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContext.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppData.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/TemplatePresenter.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/TemplatesManager.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/network/api/DefineTemplatesRequestBody.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/utils/JsonUtils.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/InAppTestUtils.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContextTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/TemplatesManagerTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManagerTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/network/api/DefineTemplatesRequestBodyTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/utils/JsonUtilsTest.kt

Add TemplatePresenter to the template definitions
Add TemplateContext API for handling template invocations. Merge template args overrides with default values and provide access to the values. Integrate template presentation in the current in-app display flow

task(MC-1460): Implement template presenting

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CTWebInterface.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFragment.java
clevertap-core/src/test/java/com/clevertap/android/sdk/CTWebInterfaceTest.kt

Add triggerAction to the JS API

task(MC-1464): Custom code templates support for html in-apps

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplate.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContext.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppData.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/TemplatesManager.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/response/InAppResponse.java
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContextTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppDataTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/TemplatesManagerTest.kt

Add access to active template contexts in CleverTapAPI

task(MC-1646): Store active template contexts in TemplatesManager

---

clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventQueueManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EventAdapter.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/TriggerAdapter.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/TriggersMatcher.kt

https://wizrocket.atlassian.net/browse/SDK-3817

task(SDK-3817) - Adds evaluation and triggering for userattributes

---

clevertap-core/src/main/java/com/clevertap/android/sdk/AnalyticsManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapFactory.java
clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
clevertap-core/src/main/java/com/clevertap/android/sdk/CoreState.java
clevertap-core/src/main/java/com/clevertap/android/sdk/LocalDataStore.java
clevertap-core/src/main/java/com/clevertap/android/sdk/ProfileValueHandler.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventMediator.java
clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventQueueManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EventAdapter.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/TriggerAdapter.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/TriggersMatcher.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/validation/Validator.java

- Delays the persistence to after inapp evaluation
- Constructs a map of userAtttibutes to be used for evaluation

task(SDK-3814) - Moves persistence after inapp evaluation

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotificationButton.java

- corrects the parcelize implementation which was dropping the text
More details : https://wizrocket.atlassian.net/browse/SDK-3881

Feat(SDK-3881): Button text not shown in Inapps

---

clevertap-core/src/main/java/com/clevertap/android/sdk/ActivityLifeCycleManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
clevertap-core/src/test/java/com/clevertap/android/sdk/ActivityLifeCycleManagerTest.kt

- Removes checkExistingInAppNotifications
- Fixes unit tests
https://wizrocket.atlassian.net/browse/SDK-3614
Requires QA to check all inApp flows resumed/paused/killed

task(SDK-3614) - Removes redundant inapps code

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java

- Adds null check before string comparison

task(SDK-3795) - Fixes NPE

---

clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java

- Reverts to 5.2.2 and handles deprecated onBackPressed in the recommended way
- This also fixes alert template related crashes when rotated

task(SDK - 3915) - Fixes dismiss callback when inapp was rotated

---

clevertap-core/src/main/res/layout-land/inbox_carousel_text_layout.xml
clevertap-core/src/main/res/layout-land/inbox_icon_message_layout.xml
clevertap-core/src/main/res/layout-land/inbox_simple_message_layout.xml
clevertap-core/src/main/res/layout/inbox_carousel_text_layout.xml
clevertap-core/src/main/res/layout/inbox_icon_message_layout.xml
clevertap-core/src/main/res/layout/inbox_simple_message_layout.xml

https://wizrocket.atlassian.net/browse/SDK-3905

Feat(SDK-3905): Remove character limit in inbox

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFullHtmlFragment.java

Fixes white screen for few urls when loaded in a cutom html inapp webview

task(SDK-3939) - Fixes white screen for few urls

---

CHANGELOG.md
README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
sample/build.gradle
templates/CTCORECHANGELOG.md

- Updates docs
- Upgrades version
- Runs copyTemplates

docs(SDK-4029) - Release cadence for 7.0.1

---

CHANGELOG.md
README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
sample/build.gradle
templates/CTCORECHANGELOG.md

https://wizrocket.atlassian.net/browse/SDK-4092

docs(SDK-4092): Release cadence for 7.0.2

---

sample/build.gradle
sample/src/main/java/com/clevertap/demo/HomeScreenActivity.kt
sample/src/main/java/com/clevertap/demo/MyApplication.kt
sample/src/main/java/com/clevertap/demo/WebViewActivity.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenFragment.kt

- initialises singleton clevertap instance in application class
- uses singleton ct instance in whole app

Chore: Make clevertap instance singleton in sample app

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/main/java/com/clevertap/android/sdk/LocalDataStore.java
clevertap-core/src/main/java/com/clevertap/android/sdk/SessionManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBManager.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventQueueManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/usereventlogs/UserEventLogDAO.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/usereventlogs/UserEventLogDAOImpl.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/CleverTapAPITest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/EventQueueManagerTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/LocalDataStoreTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/SessionManagerTest.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/usereventlogs/UserEventLogDAOImplTest.kt

Move update of LocalStore to EventQueueManager.processEvent Remove getUserEventLogFirstTs and getUserEventLogLastTs. Replace usage with getUserEventLog
Change getUserEventLogCount to return 0 when no events match

Multi-triggers updates

---

CHANGELOG.md
templates/CTCORECHANGELOG.md
templates/EXAMPLES.md

Updates md files for release core-7.1.0

Chore/multi triggers/dev docs/SDK-4219

---

clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/ExoplayerHandle.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/ExoplayerPlayerListener.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/Media3Handle.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/Media3PlayerListener.kt

Also fixes  - https://github.com/CleverTap/clevertap-android-sdk/issues/671

Task/sdk 4165/media3 abstract method error

---

clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/CoreNotificationRenderer.java

https://wizrocket.atlassian.net/browse/SDK-4228

feat(SDK-4228): adds changes to key as per comments.

---

README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
docs/EXAMPLES.md
templates/CTCORECHANGELOG.md

https://wizrocket.atlassian.net/browse/SDK-4178
Release Docs for core 7.1.0.

docs(SDK-4178): changelog for core Release 7.1.0

---

sample/build.gradle

Sample app update to latest SDK

chore(SDK-4178): updates sample app dependencies

---

clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFullHtmlFragment.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppHtmlHalfInterstitialFragment.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppHtmlInterstitialFragment.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppWebView.java

- Applies system bar and display cut outs margin to in-apps
- Measures `CTInAppWebview` using WindowManager above `Android Q`

Fixes html interstitial and html half interstitial in-apps for Android 15 SDK-4234

---

CHANGELOG.md
README.md
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
sample/build.gradle
templates/CTCORECHANGELOG.md

Release docs changes for 7.2.1 SDK-4293

---

CHANGELOG.md
README.md
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle-scripts/commons.gradle
gradle/libs.versions.toml
sample/build.gradle
templates/CTCORECHANGELOG.md

https://wizrocket.atlassian.net/browse/SDK-4293

Release core v7.2.1

---

clevertap-core/src/test/java/com/clevertap/android/sdk/cryption/CryptMigratorTest.kt
sample/build.gradle

Todo
- Tests for migrateInApp data if possible

tests(SDK-4215) - Adds UTs for CryptMigrator

---

CHANGELOG.md
README.md
clevertap-core/src/main/java/com/clevertap/android/sdk/AnalyticsManager.java
clevertap-core/src/main/java/com/clevertap/android/sdk/AnalyticsManagerBundler.kt
clevertap-core/src/test/java/com/clevertap/android/sdk/AnalyticsManagerTest.kt
docs/CTCORECHANGELOG.md
docs/CTGEOFENCE.md
docs/CTPUSHTEMPLATES.md
gradle/libs.versions.toml
sample/build.gradle
templates/CTCORECHANGELOG.md

NOTIFICATION_VIEWED event was raised instead of NOTIFICATION_CLICKED
https://wizrocket.atlassian.net/browse/SDK-4303
https://wizrocket.atlassian.net/browse/SDK-4304

task(SDK-4303) - Fixes notification clicked event not getting raised

---

CHANGELOG.md
docs/CTCORECHANGELOG.md
templates/CTCORECHANGELOG.md

docs: fixes dates and changelog for hotfix

---

.github/mini_flows/build_code_debug/action.yml
.github/mini_flows/build_code_release/action.yml
.github/mini_flows/codechecks_checkstyle/action.yml
.github/mini_flows/codechecks_detekt/action.yml
.github/mini_flows/lint/action.yml
.github/mini_flows/test_and_coverage_debug/action.yml
.github/mini_flows/test_and_coverage_release/action.yml
.github/mini_flows/test_debug/action.yml
.github/mini_flows/test_release/action.yml
.github/workflows/build_sample_app.yml

Deprecation Notice https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

chore(gitactions) - Updates actions/upload-artifact@v3 to v4

---

CHANGELOG.md

Docs Core 7.3.0, HMS 1.5.0, Push templates 1.4.0

---

clevertap-core/consumer-rules.pro
clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java
clevertap-core/src/main/java/com/clevertap/android/sdk/PushPermissionHandler.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppActionHandler.kt
clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java

Remove unused parameter from PushPermissionHandler

Add play review library proguard rule

---

clevertap-pushtemplates/src/main/res/drawable/pt_rounded_shape.xml
clevertap-pushtemplates/src/main/res/layout/manual_carousel.xml

- Removes padding from shape and adds margin to layout

task(SDK-4537) - Removes extra space from manual_carousel.xml

---

clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
clevertap-core/src/test/java/com/clevertap/android/sdk/CleverTapAPITest.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt

- Adds ui in sample app to set opt out statuses
- Fixes issue to send opt out status to server, if user was already opted out then new opt out would not work with allow system events flag update
- covers unit tests for the same

task(SDK-5026): Adds opt out UI in sample app + opt out update
