CleverTap/clevertap-android-sdk

- clevertap-android-sdk/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
Restricting the scope of the Intent for action launch to the current package to avoid failures in the cases where multiple apps using clevertap exists on the phone.
This fixes #12. Verified on Hotstar with SonyLIV installed.
> Fix for #12

- clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/CTNotificationIntentService.java
- docs/CTCORECHANGELOG.md
- docs/CTPUSHTEMPLATES.md
- docs/CTPUSHTEMPLATESCHANGELOG.md
- sample/src/main/java/com/clevertap/demo/ui/main/NotificationUtils.kt
- templates/CTCORECHANGELOG.md
- templates/CTPUSHTEMPLATES.md
- templates/CTPUSHTEMPLATESCHANGELOG.md
Fixes a bug when `dismissOnClick` is false in InputBox template across all android versions
> SDK-1804/pt_cta_weblink_fix_12

- clevertap-core/src/main/java/com/clevertap/android/sdk/CTInboxMessageListener.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/InboxMessageListener.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTCarouselImageViewHolder.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTCarouselMessageViewHolder.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTCarouselViewPagerAdapter.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTIconMessageViewHolder.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxButtonClickListener.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxListViewFragment.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTSimpleMessageViewHolder.java
- clevertap-core/src/test/java/com/clevertap/android/sdk/SessionManagerTest.kt
[SDK-1813/SDK-1910](https://wizrocket.atlassian.net/browse/SDK-1910) : onMessage Click Callback for App inbox
Goal was to receive an inbox item click and pass it to a listener provided by the client. 
The previous code was already  generating such clicks, but was passing them through the button click callback, i.e a click on message button or the message body was considered same. 
Changes:
- on the client side : user can now pass an `InboxMessageListener` in addition to `InboxMessageButtonListener` to receive inbox item click 
- internally : we pass "isBodyClick" = true/false from each of the view holder on wherever there is a click listener in CleverTapApi, we  call the user provided listeners on the basis of this boolean
> Task/sdk/sdk 1910 onMessage Click Callback for App inbox

- sample/src/main/AndroidManifest.xml
Fixes a bug where the icon of sample app does not show up when app is installed in emulator or device.It is caused due to multiple categories and actions being added in the same intent-filter.
> You can create a filter that includes more than one instance of <action>,<data>,<category>. If you do, you need to be certain that the component can handle any and all combinations of those filter elements.
> 
> When you want to handle multiple kinds of intents, but only in specific combinations of action, data, and category type, then you need to create multiple intent filters.
Full documentation can be found regarding intent-filters [here](https://developer.android.com/guide/components/intents-filters#Receiving)
> fix(chore):Add separate intent-filters for appLaunch & for handing deep links

- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/styles/Style.kt
- fixes a bug on android 12 where push template notification header was not displaying subtitle text.
> fix(push-templates): add subtitle to notification header above android 12 SDK-2160

- .github/mini_flows/build_code_debug/action.yml
- .github/mini_flows/build_code_release/action.yml
- .github/mini_flows/codechecks_checkstyle/action.yml
- .github/mini_flows/codechecks_detekt/action.yml
- .github/mini_flows/lint/action.yml
- .github/mini_flows/setup_jdk/action.yml
- .github/mini_flows/test_and_coverage_debug/action.yml
- .github/mini_flows/test_and_coverage_release/action.yml
- .github/mini_flows/test_debug/action.yml
- .github/mini_flows/test_release/action.yml
- .github/workflows/manually_validate.yml
- .github/workflows/on_pr_from_develop_to_master.yml
- .github/workflows/on_pr_from_task_to_develop.yml
- .github/workflows/on_pr_merged_in_master.yml
**Current situation** 
when a cicd pipeline is successfully ran, it generates a single zip file for all AARs in large nested folder (`build>output>aars>com>clevertap>(module) > .aar file`) . This result in large bandwidth wastage for during downloads and also does not give a correct idea about which tasks generated a successful artifact and size of independent artifacts
**What this PR proposes**
This PR splits each step of various workflows into independent module level steps. For eg, if there was a single build step before : 
```yml 
- name: Generate AAR files
shell: bash
run: ./gradlew :clevertap-core:assembleDebug :clevertap-geofence:assembleDebug  :clevertap-hms:assembleDebug  :clevertap-pushTemplates:assembleDebug :clevertap-xps:assembleDebug
```
it is split into multiple steps: …
> update cicd actions to support independent artifacts

- clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
ANR was causing due to static initialization of SimpleDateFormate on main thread. It has been removed since unused in our code.
> fix ANR SDK-2328

- clevertap-core/consumer-rules.pro
- clevertap-core/src/main/java/com/clevertap/android/sdk/ActivityLifeCycleManager.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/test/java/com/clevertap/android/sdk/ActivityLifeCycleManagerTest.kt
- add Proguard rules to keep CREATOR instance for Parcelable classes  (fixes ANR 1 from SUC-119607) 
- make call to `installReferral` async   (fixes crash 3 from SUC-119607) 
- use concurrent HashMap instead of HashMap for storing `CleverTapApi` instances (fixes crash 1 and 2 from SUC-119607) 
- update unit tests
> [SDK-2293] multiple  NOC fixes

- CHANGELOG.md
- README.md
- build.gradle
- buildSrc/src/main/kotlin/Libs.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- docs/CTCORECHANGELOG.md
- docs/CTGEOFENCE.md
- docs/CTPUSHTEMPLATES.md
- docs/CTPUSHTEMPLATESCHANGELOG.md
- docs/CTRENDERMAX.md
- docs/CTRENDERMAXCHANGELOG.md
- gradle-scripts/commons.gradle
- templates/CTCORECHANGELOG.md
- templates/CTPUSHTEMPLATESCHANGELOG.md
- templates/CTRENDERMAX.md
- templates/CTRENDERMAXCHANGELOG.md
- templates/README.md
- versions.properties
This release is being done for Android 12 targeted users, satisfying below points.
- Targeting Android 12 and
- Using RenderMax and/or using Push Templates
> Release core v4.6.7 push-templates v1.0.5.1

- clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
[SDK-2596]  setting clevertap-prod.com as PRIMARY_DOMAIN instead of wzrkt.com
[SDK-2596]: https://wizrocket.atlassian.net/browse/SDK-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDK-2596] Changes SDK endpoint 

- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PushTemplateReceiver.java
- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/PendingIntentFactory.kt
- clevertap-pushtemplates/src/main/res/layout/rating.xml
- Adds a fix where `Rating Submitted` event is raised once the confirmation button is clicked for Android 11+ devices. This behaviour will be consistent across all Android OS versions.
- Also fixed the confirmation button text visibility for Android 11+ devices.
> [SDK-2799] - 'Rating Submitted' event consistency for all Android OS versions

- clevertap-core/src/main/java/com/clevertap/android/sdk/leanplum/CTWrapper.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/leanplum/CleverTapProvider.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/leanplum/Constants.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/leanplum/LeanplumCT.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/leanplum/StartCallback.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/leanplum/LeanplumCtTest.kt
Main interface is `LeanplumCT`, which implements most of the methods of `Leanplum` class from Leanplum SDK.
It can be initialized using the following code:
```
ActivityLifecycleCallback.register(this);
LeanplumCT.initWithContext(this);
```
or by using `CleverTapAPI` instance:
```
ActivityLifecycleCallback.register(this);
LeanplumCT.initWithInstance(instance);
```
Some of the transformation code from CTWrapper in Leanplum repo has been reused.
Most use cases are handled by unit tests.
There are some notes in the [doc](https://docs.google.com/document/d/1639NoXp98ZXCyT1uuIhoVPXB_4dm2U95QylbswRdjNQ/edit).
> [SDK-2728] Leanplum Interface

- clevertap-core/src/main/java/com/clevertap/android/sdk/CTWebInterface.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapInstanceConfig.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/CoreMetaData.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkManager.java
- Passes a flag in the appFields to capture the external initialization/usage of webViewInterface done from application.
> [SDK-3064] Track events raised from webView interface

- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
https://wizrocket.atlassian.net/browse/SDK-3041
https://github.com/CleverTap/clevertap-android-sdk/issues/428
Adds an additional check just before displaying the in-app to prevent the in-app from showing on an excluded activity
> fix(SDK-3041): Adds a check to prevent in-app on excluded activity

- docs/CTPUSHTEMPLATES.md
Updated the `pt_dismiss_on_click` to a required field in order to record the **Remind** event when clicking on the Remind Later CTA.
> [SDK-3213] Update Push Templates Readme 

- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/DeviceInfo.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/utils/CTJsonConverter.java
https://wizrocket.atlassian.net/browse/SDK-3220
Adds an API to setCustomLocale for LP parity
If locale it is not custom set by client then it is fetched from the device and passed to the LC
> task(SDK-3220) - Gets locale info and pass it to LC for LP parity

- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PTConstants.java
- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PushTemplateReceiver.java
- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/PendingIntentFactory.kt
- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/RatingContentView.kt
https://wizrocket.atlassian.net/browse/SDK-3341
Fixes issue on Rating PT where clicking a star led to nothing on API 30 and below
Also addressed the scenario when 2 Rating PT are available at the same time
> task(SDK-3341) - Fixes star-click Rating PT issue

- clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PushTemplateReceiver.java
Provides support for default channel in PT. 
ChannelID is never used in PushTemplateReceiver.java. We either use silent-channel or reuse the channel on which the notification was rendered in the first place. Hence the condition can be simply removed
https://wizrocket.atlassian.net/browse/SDK-3072
> Task/sdk 3072/support for default channel pt

- docs/CTPUSHTEMPLATES.md
- templates/CTPUSHTEMPLATES.md
Updates docs for image resolution limit for five icons pt. The exact limit was found out to be 353x353 but updating docs with a limit of 300x300
> docs(SDK-3382) - Updates docs for five icons image resolution limit

- clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBAdapter.java
Handles NPE for inbox messages. If an exception was caught earlier when retrieving the messages from DB, a null was returned. Now instead, an empty list is returned
> task(SDK-3422) - Handles NPE for inbox messages

- clevertap-core/src/main/java/com/clevertap/android/sdk/CTXtensions.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/validation/ValidationResultFactory.java
- clevertap-core/src/main/res/values/strings.xml
- clevertap-core/src/test/java/com/clevertap/android/sdk/validation/ValidationResultFactoryTest.kt
https://wizrocket.atlassian.net/browse/SDK-3514
Adds ct as prefix to a default channel resource name because of conflict
> Task/sdk 3514/fallback channel resource name conflict

- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapFactory.java
StrictMode violation was seen because `ctVariables.init()` led to prefs being accessed on the main thread
https://wizrocket.atlassian.net/browse/SDK-3530
> task(SDK-3530) - Moves initialisation of ctVariables to an IO thread

- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/variables/Parser.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/variables/Var.java
- clevertap-core/src/test/java/com/clevertap/android/sdk/variables/VarCacheTest.kt
**Issue Summary:**
When a PE variable of `Long` type is defined with a null default value, and the dashboard overrides it with a Double value, The SDK throws a ClassCastException (Double cannot be cast to Long).
**Fix:**
Restricted the null usage as default value for PE variables.
> [SDK-3328] Fix classCastException from while reading PE variable

- clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventQueueManager.java
1. session creation will be skip for push impression events and sessionId will be passed as 0 for push impression events when app is in killed state.
> remove push impressions events from being considered for session length calculation SDK-3538

- clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/PushProviders.java
Moved refreshCTProviderTokens() from iO() to postAsyncSafely() to avoid parallel access to availableCTPushProviders
> Fix concurrent modification exception for availableCTPushProviders list SDK-3604

- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNativeCoverFragment.java
https://wizrocket.atlassian.net/browse/SDK-3580
(This doesn’t pertain to InApp CoverImageOnly type)
> task(SDK-3580) - Removes onClickListener for Image of Cover InApp

- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java
- clevertap-core/src/main/res/layout/inbox_activity.xml
- clevertap-core/src/main/res/layout/inbox_list_view.xml
- clevertap-core/src/main/res/values/strings.xml
Fixes no empty message for app inbox without tabs
The view for no empty message was being overlapped by the LinearLayout. It was fixed by moving it inside the linear layout
https://wizrocket.atlassian.net/browse/SDK-3559
> task(SDK-3559) - Fixes no empty message for app inbox without tabs

- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
Jira: https://wizrocket.atlassian.net/browse/SDK-3668
- xiaomi will be removed after March according to compliance
> Feat: Deprecated labels for xiaomi methods

- clevertap-core/src/main/java/com/clevertap/android/sdk/network/api/CtApi.kt
- this is due to nw refactor
- app is sending incorrect url which starts like https:/hello.....
- fixed the issue with having default when null
> Bug: Domain issue in handshake

- clevertap-core/src/main/AndroidManifest.xml
Removes CTBackgroundIntentService and CTBackgroundJobService from AndroidManifest.xml
- These entries caused crashes in v6.1.0 and v6.1.1. Workaround was provided for client then. 
- It will now be fixed in the SDK itself
> task(SDK-3713) - Removes entries for pushamp related classes

- CHANGELOG.md
- README.md
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapInstanceConfig.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
- docs/CTCORECHANGELOG.md
- docs/CTGEOFENCE.md
- docs/CTPUSHTEMPLATES.md
- gradle/libs.versions.toml
- templates/CTCORECHANGELOG.md
This hotfix release addresses the following issue in `v6.2.0`:
* Fixes a crash `IllegalArgumentException` caused by `allowedPushType` XPS enum.
> Release core v6.2.1 SDK-3760 SDK-3759

- .github/workflows/build_sample_app.yml
- .github/workflows/manually_validate.yml
- CHANGELOG.md
- README.md
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapInstanceConfig.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
- docs/CTCORECHANGELOG.md
- docs/CTGEOFENCE.md
- docs/CTPUSHTEMPLATES.md
- gradle/libs.versions.toml
- sample/build.gradle
- sample/src/main/AndroidManifest.xml
- templates/CTCORECHANGELOG.md
This hotfix release addresses the following issue in `v6.2.0`:
* Fixes a crash `IllegalArgumentException` caused by `allowedPushType` XPS enum.
Sample App Related
* Adds a workflow to manually build apps from git actions
* Fixes the manually validate workflow
> Release core v6.2.1 SDK-3760

- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplate.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContext.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContextTest.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateTest.kt
Move map argument methods to the base classes CustomTemplateContext and CustomTemplate.Builder
> task(MC-1648): Allow map arguments and argument nesting in functions

- clevertap-core/src/main/java/com/clevertap/android/sdk/CTXtensions.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/data/InAppResponseAdapter.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/CTXtensionsTest.kt
https://wizrocket.atlassian.net/browse/SDK-3853
Fix 
- Even when an empty JSoN array is received in response for `inapp_notifs_cs`, save it 
- Same is done for `inapp_notifs_ss`  for clarity even though it will not cause any issue previously
> task(SDK-3853) - Fixes Stopped/Deleted campaign is not cleared in the SDK in ClientSide mode

- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/StoreProvider.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppType.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/data/InAppResponseAdapter.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/FileResourceProvider.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObject.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryAccessObjectV1.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryAccessObjectV1.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/MemoryCreator.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderExecutors.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepo.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoImpl.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/task/CTExecutors.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/utils/FileCache.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/variables/VarCache.java
1. Fix count down logic of CountDownLatch in `FilePreloaderExecutors`
> DEV QA fixes SDK-3893

- clevertap-core/src/main/java/com/clevertap/android/sdk/DeviceInfo.java
Calling `getDeviceID()` second time returns null value during AND operation.
This PR fixes it by calling `getDeviceID()` only once and collect it in val for reuse in AND operation.
> Fix NullPointerException caused during device id fetch SDK-3773

- clevertap-core/src/main/java/com/clevertap/android/sdk/login/LoginController.java
- Start postAsyncSafely earlier to prevent race conditions in case of custom clevertap-id
- Remove lock as postAsyncSafely and onUserLogin will now always run one after the other
- Race condition was due to `onUserLogin` running on the client's thread and `asyncProfileSwitchUser` on the executor thread. The deviceId was not updated yet and hence asyncProfileSwitchUser was called once from getDefaultInstance and again when the user logged in immediately
> Task/sdk 3898/app launched repeated

- clevertap-core/src/main/java/com/clevertap/android/sdk/video/VideoLibChecker.kt
- Improves redundant logs
- Earlier `Logger.d("ExoPlayer classes not found " + className.getName())` printed not found for incorrect class. This was fixed as well
> task(SDK-3780) - Fix misleading logs for exoplayer

- clevertap-core/src/main/java/com/clevertap/android/sdk/variables/VarCache.java
Fixes an issue where variables weren't reset to default values when user switched
Issue was found when refactoring unit tests
> task(SDK-3922) - clear variables when user switch

- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/FileResourceProvider.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/FileResourceProviderTest.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderCoroutineTest.kt
Jira: https://wizrocket.atlassian.net/browse/SDK-3936
- avoids crash cause we checked success status of api before forcing bytes/bitmap from response
- checks for api http status were missing
- adds test cases to validate the failure cases and correctness of responses for succ/failure
> Feat(SDK-3936): Handles failure in fetch asset api

- clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFragment.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppListener.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContext.kt
Remove redundant Context argument from inAppNotificationDidDismiss and use the Context of InAppController every time.
> fix(MC-1881): Fix NPE for Context in in-app dismiss

- CHANGELOG.md
- README.md
- clevertap-core/src/main/java/com/clevertap/android/sdk/CallbackManager.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppAction.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFragment.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTLocalInApp.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/login/LoginController.java
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/CTLocalInAppTest.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/login/LoginControllerTest.kt
- docs/CTCORECHANGELOG.md
- docs/CTGEOFENCE.md
- docs/CTPUSHTEMPLATES.md
- gradle/libs.versions.toml
- sample/build.gradle
- templates/CTCORECHANGELOG.md
* Fixes an issue related to `ArrayIndexOutOfBoundsException` in a rare `race condition` scenario.
* Fixes an issue where the Android Permission popup is not triggered from `PushPrimer` when using `InAppType.HALF_INTERSTITIAL`
> Release corev7.0.1

- clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppBaseFragment.java
This fixes tracking callToAction if it exists as a parameter to the links opened from the in-apps webview. There is also a frontend fix directly in the in-app HTML, that would use triggerAction instead of opening links.
> bug(MC-2299): Fix c2a param not tracked for open_url and close actions

- clevertap-core/src/main/java/com/clevertap/android/sdk/LocalDataStore.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/db/CtDatabase.kt
Change the cached user event log keys set to contain the normalized event names to match the db logic Reorder deviceID column in the primary key of UserEventLog table to speed up allEventsByDeviceID query
> Add minor optimiziations to UserEventLog operations

- clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventQueueManager.java
- clevertap-core/src/test/java/com/clevertap/android/sdk/EventQueueManagerTest.kt
extract in-app eval code in ` initInAppEvaluation()` and reuse it in `processPushNotificationViewedEvent()`
> fix missing in-app evaluation on notification viewed event SDK-4229

- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
Issue happened in below code
fun loadSuppressedCSAndEvaluatedSSInAppsIds() {
storeRegistry.inAppStore?.let { store ->
evaluatedServerSideCampaignIds.putAll(JsonUtil.mapFromJson(store.readEvaluatedServerSideInAppIds()))
suppressedClientSideInApps.putAll(JsonUtil.mapFromJson(store.readSuppressedClientSideInAppIds()))
}
}
1. `store.readEvaluatedServerSideInAppIds()` returns in-app Ids as `Int` instead of `Long` and `evaluatedServerSideCampaignIds` expects in-app Ids as `Long` 
2. Below` 7.2.0` it was working as expected but in `7.2.0` we bumped kotlin version to `2.0.10` which caused an issue.
3. Kotlin created strict rule regarding `Int` and `Long` comparison inside lambda. Basically it’s not allowed to compare `Int` with `Long` in lambda from `1.8.0` onwards. 
- …
> fix(ss_inapps) - fix in-app id data type conversion from Int to Long fo SS in-apps SDK-4246

- CHANGELOG.md
- README.md
- docs/CTCORECHANGELOG.md
- docs/CTGEOFENCE.md
- docs/CTPUSHTEMPLATES.md
- gradle/libs.versions.toml
- sample/build.gradle
- templates/CTCORECHANGELOG.md
Addresses a fix related to JDK version when generating aar for core sdk.
- bump core version to `7.1.2`
- update docs for release `7.1.2`
- downgrade sample app dependency for `google-services-ads` from `23.6.0` to `22.6.0` due to build error.
> Release 7.1.2 SKD-4348

- clevertap-core/src/main/java/com/clevertap/android/sdk/DidClickForHardPermissionListener.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java
- clevertap-core/src/main/java/com/clevertap/android/sdk/PushPermissionHandler.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTLocalInApp.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/fragment/CTInAppBaseFragment.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java
We are trying to achieve the following change in behaviour
**Half-Inter**
1. For  Allow button clicked Add actionExtras -> {wzrk_c2a = "Allow", wzrk_id = ""}  to onDismissed callback
2. For  Deny button additional onPushPermissionResponse with accepted -> false
**Alert**
1. For  Allow button clicked Add actionExtras -> {wzrk_c2a = "Allow", wzrk_id = ""}  to onDismissed callback
2. For  Deny button clicked Add actionExtras -> {wzrk_c2a = "Deny", wzrk_id = ""}  to onDismissed callback
3. For  Deny button additional onPushPermissionResponse with accepted -> false
Not raise click event for close button
Backlog -> Dismiss local inapp first and then show the OS prompt like system inapp functions
> task(SDK-5031) - Local Inapp parity with iOS

- clevertap-core/src/main/java/com/clevertap/android/sdk/db/BaseDatabaseManager.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBAdapter.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/db/DBManager.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/db/QueueData.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/store/preference/InAppStore.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkHeadersListener.kt
- clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkManager.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/db/DBManagerTest.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManagerTest.kt
- clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/store/preference/InAppStoreTest.kt
- removes separate handling as it is not needed
- reverts back to original way of saving data for suppressed and eval modes.
> task(SDK-5186): Handles evaluation for profile and raised events
